spring:
  datasource:
    url: 'jdbc:h2:mem:test'
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

management:
  server:
    address: 127.0.0.1
    port: 9000
  security:
    enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /
    disable-swagger-default-url: true

web3j:
  client-address: 'http://localhost:9545'

wallet:
  directory:
    path: '${java.io.tmpdir}'

#Override private key from ganache created account to make deposits
ganache:
  account:
    privatekey: 
